actions:
  - id: 1
    name: praise
    source:
      physic:
        id: 1
      psychology:
        id: 1
    target:
      physic:
        id: 1
      psychology:
        id: 1
    expression:
      - index: 5
        command: tmp.happy = target.psychology.attribute.psychology_index.happy.toInt()
      - index: 10
        command: target.psychology.attribute.psychology_index.happy = int(tmp.happy + (100-tmp.happy) * 0.1).toString()
  - id: 2
    name: insults
    source:
      physic:
        id: 1
      psychology:
        id: 1
    target:
      physic:
        id: 1
      psychology:
        id: 1
    expression:
      - index: 5
        command: tmp.angry = target.psychology.attribute.psychology_index.angry.toInt()
      - index: 10
        command: target.psychology.attribute.psychology_index.angry = int(tmp.angry + (100-tmp.angry) * 0.1).toString()